# ~/.config/starship.toml


# A minimal left prompt
format = """$all"""

# move the rest of the prompt to the right
right_format = """$nodejs$cmd_duration"""

add_newline = false

[character]
error_symbol = "[â¯](bold red) "

[cmd_duration]
min_time = 1                   # Show command duration over 10,000 milliseconds (=10 sec)
format = "[$duration]($style)"

[directory]
truncation_length = 10
format = "[ï¼ ](bold blue)[$path]($style)[$lock_symbol]($lock_style)"
home_symbol = "~"
truncate_to_repo = false

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ï„¦ "
style = "bold #00DA00"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "[â†‘${count} ](bold #00DA00)"
behind = "[â†“${count} ](bold #00DA00)"
diverged = "[â†‘${ahead_count}â†“${behind_count} ](bold #00DA00)"
untracked = "[?${count} ](bold #00B2FF)"
stashed = "[*${count} ](bold #00DA00)"
modified = "[!${count} ](bold #DEAC00)"
staged = "[+${count} ](bold #DEAC00)"
renamed = "ğŸ“› Ã—${count} "
deleted = "[âœ˜${count} ](bold 160)"
style = "bright-white"
format = "$ahead_behind$all_status"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = "-"
style = "bold dimmed white"
disabled = true

[java]
disabled = true

[julia]
format = "[$symbol$version]($style) "
symbol = "à®ƒ "
style = "bold green"

[package]
disabled = true

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[sudo]
symbol = 'ğŸ”'

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = true

[typst]
format = "[$symbol($version)]($style)"
style = "bold #239dae"

[username]
style_user = "bold dimmed blue"
show_always = false

[nodejs]
format = "[node $version](bold green) "
disabled = true
